### PR TITLE
Update from sklearn to scikit-learn

### PR DESCRIPTION
**Pull request by bbimber**
@xhongyi: I hope you're still monitoring this repo. sklearn updated to scikit-learn, and this PR is trying to fix this. It seemed like you only had one usage of this package, which appears to be unchanged between scikit-learn versions.

### CODE REVIEW

**Comment by bbimber** [comment]
@xhongyi: is anyone still overseeing this repo?

**Comment by bbimber** [comment]
@xhongyi: I see you made commits about 6 months ago. Would you consider these, which update GMMDemux to work with newer scipy?

**Comment by Zethson** [comment]
@xhongyi ?

**Comment by bbimber** [comment]
Note, this is adds a commit to restore the ability to set random_state, which allows one to get deterministic behavior from the output. That behavior was lost with the last commit, i assume unintentionally.

**Comment by xhongyi** [comment]
Hi all,

Sorry for the late reply. I have moved to China and no longer get automatic reply notifications.

I have just run a maintenance today and updated the repo to be compatible with both the scipy and the sklearn updates.

Let me check the conflicts and I'll see if I can merge them.

Thanks @bbimber for helping with the repo! Appreciated!

Hongyi

**Comment by xhongyi** [comment]
I have taken a look at your code @bbimber. They are all proper. However, my Github app has just swapped all spaces with tabs or sorts and sort of created a massive code diff and conflict.
I have already incorporated all of your changes. I guess I've taken your code modifications by hand 😂.
If there is nothing else, I'm closing the request.

**Pull request closed without merging**
